### ISSUE TITLE
Open AI connect ...

### ISSUE THREAD

**Issue by rrac** [microsoft/vscode-jupyter-slideshow#11] opened 2023-05-09 20:34 UTC
Type: <b>Bug</b>

Attempting simple prompts on Open AI using Python.

Extension version: 0.1.5
VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (17.15GB free)|
|Process Argv|--crash-reporter-id c6630875-31d6-4142-8fa6-4599e1074f98|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpath:30731978

```

</details>

**Comment by DonJayamanne** [comment] 2023-05-09 20:47
Thank you for filing this issue, however there is insufficient information in this to help us help you
Is this a bug or was this issue automatcailly filed, what is the expected behaviour vs actual behaviour or what are the steps to repro the issue
Closing this issue for now due to lack of information

Please feel free to create a new issue with the necessary information or update this and I can re-open this or feel free to reopen it.

**Closed as completed by DonJayamanne** 2023-05-09 20:47 UTC
