### ISSUE TITLE
Cannot Switch Slide Type Unless the JSON Metadata is Already Populated

### ISSUE THREAD

**Issue by Mjvolk3** [microsoft/vscode-jupyter-slideshow#2] opened 2022-09-22 04:03 UTC
Cannot add slide type after typing or selecting from the available types.

![image](https://user-images.githubusercontent.com/48566106/191655227-babee294-57eb-4690-8b2c-483cbb361a43.png)

Slide type only appears if I directly edit the JSON. After doing this I can select switch slide type and it allows me to switch.

![image](https://user-images.githubusercontent.com/48566106/191655474-10f7a079-b165-4bfd-bf76-4b2a774cef91.png)

When trying to switch slide type with the command palette I get the following error message. 

![image](https://user-images.githubusercontent.com/48566106/191655889-077ab948-e6e7-4f4d-b202-a381bf17bf58.png)

VsCode Version: 1.71
OS: macOS Monterey Version 12.6

**Comment by rebornix** [comment] 2022-09-22 20:09
@Mjvolk3 thank for the issue report, it should be fixed in next version.

**Closed as completed** 2022-09-22 20:08 UTC

**Comment by rebornix** [comment] 2022-09-22 20:36
Actually it's not fixed. There was a bug in VS Code core that led to this. It's already fixed in latest Insiders but not the Stable version. The up coming VS Code stable will have this fixed.

**Comment by rebornix** [comment] 2022-09-22 21:01
The root cause is for newly created cell, we didn't handle the missing metadata properly.
