### ISSUE TITLE
Please Publish to OpenVSX Marketplace :pray: 

### ISSUE THREAD

**Issue by trinitronx** [microsoft/vscode-jupyter-slideshow#18] opened 2023-08-26 23:23 UTC
Hello!

I'm sure there are also others who would love to use this extension but currently can't find it due to the split between OpenVSX / VisualStudio Marketplace repos for OSS builds of VSCode.

In the past few years, many OSS Linux packagers of VSCode, VSCodium, (a.k.a. Code OSS) have moved to using [OpenVSX extension Registry][openvsx] and had to [disable Microsoft's Extensions Marketplace by default][1] due to Microsoft's licensing restrictions (whether they be perceived or actual :shrug:).

So, in order for most Linux developers using stock OSS-packaged versions of VSCode to find extensions such as this one, it's important to also publish to OpenVSX.

It seems like it's pretty simple to implement dual publishing via a [GitHub Actions workflow described here][doc]. It probably wouldn't take very long to accomplish and in addition would allow for easy deployment through GitHub Actions CI/CD.

[1]: https://www.reddit.com/r/vscode/comments/kb0eb5/extensions_missing/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1
[openvsx]: https://open-vsx.org/
[doc]: https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md

Below is some more info from OpenVSX's extension publishing letter template:

# OpenVSX Info / Request Template
Dear extension author, Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by isidorn** [comment] 2023-09-20 14:02
No current plans to do this.
Suggestion is to use the official VS Code build that should be installable on any Linux distribution. Thanks for understanding.

**Comment by trinitronx** [comment] 2023-09-25 13:21
> should be installable on any Linux distribution

Yes it **_should_**, but that is an incorrect assumption.

This is the problem actually... the official build does not support Wayland yet, nor ArchLinux and many other distros.  Only Ubuntu, RHEL and distros using `.rpm` / `.deb` and X11 are well supported.  VSCode suffers from an immediate crash bug on startup (microsoft/vscode#184124) for distros that have moved to use Wayland.

In fact, on ArchLinux & `pacman`-based distros, only the OSS variant of VSCode is supported, and it's increasingly difficult to even install the "official" version.

**Comment by isidorn** [comment] 2023-09-25 13:31
Thanks for clarifying. Well, that is the root cause we should be looking to fix here.
I see Deepak has that issue assigned to September so I expect it to get fixed soon-ish.
For ArchLinux, I am not sure what is missing there. Can you file a new issue and we can investigate this in the future (if one does not already exist)?

Also technically is OSS works on some Linux distro then VS Code should also work. 

Thanks 🙏

**Closed as completed** 2024-12-10 11:10 UTC
